### ISSUE TITLE
Support for markdown messages

### ISSUE THREAD

**Issue by Cadair** [opsdroid/connector-matrix#29]
It would probably be nice if we could auto-html markdown now we can send HTML messages.

**Comment by szimszon** [comment]
What could be the use case here?
As we run skills it could just produce html itself...

**Comment by Cadair** [comment]
Actually, thinking about it a little more, I think this should wait until the opsdroid/opsdroid#536 is resolved, so we can differentiate between plain text messages and markdown ones.
