### ISSUE TITLE
Become an official connector

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/connector-matrix#5]
Hey @SolarDrew & @Cadair, awesome work! It's great to see you taking the time to create your own connector for opsdroid.

Would you be interested in making this an official connector by moving the repo over to the opsdroid org?

You will of course still retain control over the repo and be the primary maintainers, it would just result in the connector being listed on the opsdroid website and allow users to install it without specifying the repo url.

If you want to move it over please go into the repo settings and change the ownership to me (@jacobtomlinson), I will then move it over to `opsdroid`. I will ensure you have full admin control on the repo, although I think that happens by default when transferring.

**Note: If you do want to make it official it will be affected by opsdroid/opsdroid#286, which I see as a good thing! But you should be aware of it if you're not already.**

**Comment by SolarDrew** [comment]
Hi @jacobtomlinson . Count us in, I'd love for this to be an official connector. I'll change the ownership now.

**Comment by jacobtomlinson** [comment]
@SolarDrew great that's all done. Thanks! 

You are still the admin and I hope you continue to maintain it and contribute to it.
